all:
	$(MAKE) -j -C 01-hello-world
	$(MAKE) -j -C 02-loader
	$(MAKE) -j -C 03-ledspiel
	$(MAKE) -j -C 04-usbdebug

clean:
	$(MAKE) clean -C 01-hello-world
	$(MAKE) clean -C 02-loader
	$(MAKE) clean -C 03-ledspiel
	$(MAKE) clean -C 04-usbdebug
